kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ rbac_namespace }}
  name: namespace-{{ rbac_group }} 
rules:
- apiGroups: [{{ api_groups }}]
  resources: [{{ resources }}]
  verbs: [{{ verbs }}]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ rbac_namespace }}
  name: namespace-{{ rbac_group }} 
subjects:
- kind: Group
  name: namespace-{{ rbac_group }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-{{ rbac_group }} 
  apiGroup: rbac.authorization.k8s.io