kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-{{ rbac_group }}
rules:
- apiGroups: [{{ api_groups }}]
  resources: [{{ resources }}]
  verbs: [{{ verbs }}]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-{{ rbac_group }}-global
subjects:
- kind: Group
  name: cluster-{{ rbac_group }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-{{ rbac_group }}
  apiGroup: rbac.authorization.k8s.io